### ISSUE TITLE
Remove repititive code 

### ISSUE THREAD

**Issue by srbmaury** [srbmaury/quiz1#11]
There is a lot of repititive code for each question. Questions and their correct answers can be fetched from some javascript object using for loop.

**Comment by Abhishek-Mallick** [comment]
Could you please assign this to me?

**Comment by srbmaury** [comment]
> Could you please assign this to me?

I have written such repetitive codes for each problem 
See if you can manage it by using some problems array.

![image](https://github.com/srbmaury/quiz1/assets/85755081/9f0d8b3c-314a-4b72-93d1-99b8aad1fc6e)

**Comment by ratishjain12** [comment]
Hey @srbmaury I can create array of object with each quiz parameters and use map function or for loop to do this task

If you assign it to me I can start working on this asap under hacktoberfest
