### ISSUE TITLE
Redesign the footer with a responsive design

### ISSUE THREAD

**Issue by Shanb98** [srbmaury/quiz1#20]
I'd like to modify the footer and make it responsive. If you want me to work on this please assign me under Hacktoberfest topic.

**Comment by srbmaury** [comment]
Currently, there is no footer. Are you willing to add one?

**Comment by Shanb98** [comment]
Yes. I would like to  add one.

**Comment by srbmaury** [comment]
there is no need for that as of now.

**Comment by ratishjain12** [comment]
Hey @srbmaury we can just add a project title alongside github repo link with icon as a footer which will make it look better do let me know please :)

**Comment by tamago01** [comment]
Would like to work on this if it's still available.
