### ISSUE TITLE
Make the website more interactive by adding more random questions or ask the user on which topic they want to take the quiz

### ISSUE THREAD

**Issue by AkuSarma** [srbmaury/quiz1#22]

**Comment by srbmaury** [comment]
Hey @AkuSarma are you willing to work on this?

**Comment by AkuSarma** [comment]
Sorry I was busy in my class assignments. I will work on it now

**Comment by srbmaury** [comment]
> Sorry I was busy in my class assignments. I will work on it now

Ok go ahead

**Comment by AkuSarma** [comment]
Hey @srbmaury I don't think I will be able to complete it better assign it to others. This university is literally not giving me any time
