### ISSUE TITLE
text is out of boundary 

### ISSUE THREAD

**Issue by mohitahlawat2001** [srbmaury/quiz1#24]
i correct this issue in pr #23 
<img width="377" alt="image" src="https://github.com/srbmaury/quiz1/assets/65100859/611db81d-5e96-4d3d-ad8d-a2af728a0a91">

please accept this with hacktoberfest label

**Comment by mohitahlawat2001** [comment]
Please add Hacktoberfest and Hacktoberfest-accept label 🙏🏻 
for hacktoberfest2023

**Comment by srbmaury** [comment]
> Please add Hacktoberfest and Hacktoberfest-accept label 🙏🏻 for hacktoberfest2023

To be accepted in Hacktoberfest either the repository should have a Hacktoberfest label or The PR should have a Hacktoberfest-accepted label (any of them will do the job) and this repository already has a Hacktoberfest label.

Please avoid writing such unnecessary comments everywhere.
