### ISSUE TITLE
[feat] : Add better error msg when user don't enter name

### ISSUE THREAD

**Issue by love-sonkar** [srbmaury/quiz1#35]
We can give a nice error msg when user presses next button without entering name.

# screenshot

![eee](https://github.com/srbmaury/quiz1/assets/82786865/7c876667-bec3-4fa6-9155-7debcf4fbbb6)

# video 
https://github.com/srbmaury/quiz1/assets/82786865/12e5ca29-bc00-45a9-8010-33b4fe86d35c

please assign me this under hacktoberfest label

**Comment by srbmaury** [comment]
What better message it could be? Can you please tell me?

**Comment by srbmaury** [comment]
One suggestion I want to give: instead of showing the default alert component can you use some kind of toast to show that?

**Comment by love-sonkar** [comment]
okay i can create a toast to show the error

**Comment by love-sonkar** [comment]
hey i have added the toast notification you can check and please accept under hacktoberfest label thankyou

**Comment by srbmaury** [comment]
Solved in #36
