### ISSUE TITLE
feat: Get category based quiz questions 

### ISSUE THREAD

**Issue by Gobinath-B** [srbmaury/quiz1#37]
### Get category based quiz questions dynamically using trivia api

**Comment by srbmaury** [comment]
Hey @Gobinath-B are you willing to work on this ?

**Comment by Gobinath-B** [comment]
Actually I'm working on other many issues, you can assign anyone who is intrested to work on this issue

**Comment by neenad99** [comment]
Hi please assign me this issue

**Comment by neenad99** [comment]
hi @srbmaury  please review the pr under hacktoberfest and add label for it

**Comment by neenad99** [comment]
currently i have only fetched quiz questions related to sports category but we can take category as input from user and generate repective questions from api

**Comment by neenad99** [comment]
please let me know about any other modifications if we can do
