### ISSUE TITLE
Make a modern UI

### ISSUE THREAD

**Issue by Ujjwal807** [srbmaury/quiz1#4]
UI is not modern by fixing this can improve user Experience

**Comment by srbmaury** [comment]
would you like to work on this?

**Comment by Ujjwal807** [comment]
Yes, I want to work on this issue.

**Comment by Ujjwal807** [comment]
Why do you close this issue I have done the work and I want to contribute.

**Comment by srbmaury** [comment]
> Why do you close this issue I have done the work and I want to contribute.

After merging your PR the UI was looking very weird as I have already sent a screenshot there. Someone else already has given a better UI which is live now.

**Comment by Ujjwal807** [comment]
I have created a Good UI if you open this so i can show this to you
