### ISSUE TITLE
[Bug] : Submit button is broken when you finish quiz the submit btn is overflow

### ISSUE THREAD

**Issue by love-sonkar** [srbmaury/quiz1#52]
**Describe the bug**
when you finish the quiz the submit button in broken the text is overflow from button and the button size is also not good

**Expected behavior**
the text should be inside in the button and increase the size of button or fix any margin padding issue to fix this bug

**Screenshots**
![btn](https://github.com/srbmaury/quiz1/assets/82786865/49e82960-c606-49b6-8604-a5352a42658e)

![btnhover](https://github.com/srbmaury/quiz1/assets/82786865/c8102306-4e0f-4f29-85e8-394b0d1a6ce6)

**Comment by srbmaury** [comment]
Please also fix any other button or overflow issue. As return button may also be improved.

**Comment by love-sonkar** [comment]
sure should i also work on prev button

**Comment by srbmaury** [comment]
Yes, please do.
