### ISSUE TITLE
add options for user to select quiz category and quiz difficulty

### ISSUE THREAD

**Issue by neenad99** [srbmaury/quiz1#53]
**Is your feature request related to a problem? Please describe.**
current quiz questions are only related to sports category so wanted to add option for user to select quiz category as well as difficulty of questions and accordingly generate questions with help of trivia api

**Describe the solution you'd like**
add UI for user to select quiz category and quiz difficulty
similarly make changes in main.js to modify url with params based on the selected options by user

**Comment by neenad99** [comment]
Hi @srbmaury  please assign me this issue under hacktoberfest

**Comment by neenad99** [comment]
this issue is further modification to this pr [#44](https://github.com/srbmaury/quiz1/pull/44)

**Comment by neenad99** [comment]
Hi @srbmaury added my changes was trying to add one more option to select no of quiz questions but figured lot of existing logic need to be changed in main.js

**Comment by neenad99** [comment]
will add that changes in seperate pr if possible

**Comment by srbmaury** [comment]
> will add that changes in seperate pr if possible

Leave it for now.
