### ISSUE TITLE
Website is not responsive

### ISSUE THREAD

**Issue by vinitsingh-13** [srbmaury/quiz1#6]
assign this to me

**Comment by guntarakesh** [comment]
@srbmaury ,  i want to work on this issue , can you assign it to me under Hacktoberfest ?

**Comment by guntarakesh** [comment]
![image](https://github.com/srbmaury/quiz1/assets/99466056/9140ab01-4417-4194-b956-5a555701d0aa)
 I want to make this responsive in Mobile .

**Comment by guntarakesh** [comment]
@srbmaury please add the Hacktoberfest label .

**Comment by vinitsingh-13** [comment]
UI is to simple assign me so that i can make a better UI

**Comment by srbmaury** [comment]
> UI is to simple assign me so that i can make a better UI

I believe @guntarakesh is already working on UI. Your changes may contradict each other.

**Comment by guntarakesh** [comment]
Yes , i am working on this issue .

**Comment by vinitsingh-13** [comment]
ok let him complete after the completion if there is any issue or any any bug left i will them
