### ISSUE TITLE
on clicking "Enter" key form is not getting submitted.

### ISSUE THREAD

**Issue by yashrajb** [srbmaury/quiz1#9]
I've noticed that there's an issue with submitting quiz responses in the project. the form does not submit when the user presses the "Enter" key. This is very bad user experience.

Currently, this project uses a div to wrap the input field and the submit button instead of a form tag. Consequently, pressing the "Enter" key does not trigger the form submission, as is commonly expected.

please assign this issue to me. i will create PR shortly

**Comment by srbmaury** [comment]
I had made this project as an absolute beginner.

Do you want to do fixes?

**Comment by yashrajb** [comment]
Yes please assign it to me

**Comment by yashrajb** [comment]
https://github.com/srbmaury/quiz1/pull/25 

@srbmaury take a look on MR
